language: go

go:
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux
  - osx

allow_failures:
  - go: tip

sudo: false

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install: true

env:
  - GO111MODULE=on

script:
  - go build
  - go test
  - $GOPATH/bin/goveralls -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)